---
version: "3.8"
services:
  movies:
    image: bsal694/movies:latest
    ports:
      - 81:80
    deploy:
      replicas: 1
  train:
    image: bsal694/train:latest
    ports:
      - 82:80
    deploy:
      replicas: 1
  dth:
    image: bsal694/dth:latest
    ports:
      - 83:80
    deploy:
      replicas: 1
  recharge:
    image: bsal694/recharge:latest
    ports:
      - 84:80
    deploy:
      replicas: 1
